spring:
  datasource:
    username: root
    password: 123456
#    url: jdbc:mysql://81.69.36.77:3306;database=EnglishWeb
    url: jdbc:mysql://81.69.36.77:3306/EnglishWeb?serverTime=UTC&useUnicode=true&characterEncoding=utf-8
    #    ?serverTime=UTC&useUnicode=true&characterEncoding=utf-8
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # 初始化连接数量
    #    initialSize: 5
    #    # 最大连接数
    #    maxActive: 10
    #    # 最大等待时间
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  #    maxWait: 3000
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database: sql_server
#    open-in-view: false
